### 查询课程信息
GET http://localhost:63010/content/course/178

### 携带token访问资源服务
GET http://localhost:63040/content/course/175
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibGVhcm5lYXN5LXBsdXMiXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjkzODIxMjYyLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiIzOWNiMGFiZC1mYTY3LTRjYzMtOGE2Ni00ZTAxMzk0MWUzODYiLCJjbGllbnRfaWQiOiJMZVdlYkFwcCJ9.HFpKNUusxgOkNrq2v3cxnY8yTKamBmIo5jsQrHnk_5g

### 通过网关访问资源服务
GET http://localhost:63010/content/course/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibGVhcm5lYXN5LXBsdXMiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjMtMDgtMjFUMDk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjMtMDgtMjFUMTA6NDg6MDFcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS54dWVjaGVuZy1wbHVzLmNvbS9kZGRmXCIsXCJ1dHlwZVwiOlwiMTAxMDAxXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5Mjc2NTAyMywiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiZmI2MTRkMzktNTdjZC00NGY1LWJjNzMtZGMzNGIwZjZiZjFmIiwiY2xpZW50X2lkIjoiTGVXZWJBcHAifQ.45K0T3iV9MsCTwttP6za1Ih7kaPPR1M3ZjsyTlzBtt0